---
title: "P8105_HW6_jl7035"
author: "Jeffrey Lin"
date: "2024-12-02"
output: html_document
---

# Load Libraries
```{r}
library(tidyverse)

```

# Problem 1 

## Load and Clean Data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```
## Peform Boostrap
```{r}
bootstrap_df <- weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, \(samp) lm(tmax ~ tmin, data = samp)),
    results = map(models, broom::tidy),
    summary = map(models, broom::glance),
    r_squared = map_dbl(summary, \(x) x$r.squared),
    log_beta_prod = map_dbl(results, \(x) log(prod(x$estimate)))
  ) %>% 
  select(-models,-results, -summary, -strap)
```

## Distribution of R-squared

```{r}
bootstrap_df %>% 
  ggplot(aes(x = r_squared)) +
  geom_density() + 
  xlab(label = "R-Squared") +
  ggtitle(label = "Distribution of R-Squared Values")

```
Examining the distribution of R-squared values, it appears that the R-squared 
for a linear model with minimum temperature as a predictor of max temperature 
tends to center at a little above 0.91. 

## Distribution of log(beta_1 * beta_0)

```{r}
bootstrap_df %>% 
  ggplot(aes(x = log_beta_prod)) + 
  geom_density()
```


```{r}

```


# Problem 2 

# Problem 3
